// File: main/java/com/aquaa/edusoul/viewmodels/SyllabusTopicViewModel.kt
package com.aquaa.edusoul.viewmodels

import android.util.Log
import androidx.lifecycle.LiveData
import androidx.lifecycle.MutableLiveData
import androidx.lifecycle.ViewModel
import androidx.lifecycle.asLiveData
import androidx.lifecycle.switchMap
import androidx.lifecycle.viewModelScope
import com.aquaa.edusoul.models.SyllabusProgress
import com.aquaa.edusoul.models.SyllabusTopic
import com.aquaa.edusoul.models.SyllabusTopicStatusAdmin
import com.aquaa.edusoul.repositories.SyllabusProgressRepository
import com.aquaa.edusoul.repositories.SyllabusTopicRepository
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.combine
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext
import kotlinx.coroutines.flow.map
import kotlinx.coroutines.flow.firstOrNull // Import firstOrNull for flow
import java.text.SimpleDateFormat
import java.util.Date
import java.util.Locale

class SyllabusTopicViewModel(
    private val syllabusTopicRepository: SyllabusTopicRepository,
    private val syllabusProgressRepository: SyllabusProgressRepository
) : ViewModel() {

    private val TAG = "SyllabusTopicViewModel"

    private val _selectedSubjectAndBatch = MutableLiveData<Pair<String?, String?>>()

    val syllabusTopicsWithStatus: LiveData<List<Pair<SyllabusTopic, Boolean>>> =
        _selectedSubjectAndBatch.switchMap { (subjectId, batchId) ->
            if (!subjectId.isNullOrBlank()) {
                syllabusTopicRepository.getTopicsForSubject(subjectId).combine(
                    if (!batchId.isNullOrBlank()) syllabusProgressRepository.getSyllabusProgressForBatch(batchId)
                    else kotlinx.coroutines.flow.flowOf(emptyList())
                ) { topics, progresses ->
                    val progressMap = progresses.associateBy { it.syllabusTopicId }
                    topics.map { topic ->
                        val isCompleted = progressMap[topic.id]?.isCompleted ?: false
                        Pair(topic, isCompleted)
                    }
                }.asLiveData(Dispatchers.IO)
            } else {
                MutableLiveData(emptyList())
            }
        }

    private val _isLoading = MutableLiveData<Boolean>()
    val isLoading: LiveData<Boolean> get() = _isLoading

    private val _errorMessage = MutableLiveData<String?>()
    val errorMessage: LiveData<String?> get() = _errorMessage

    fun clearErrorMessage() {
        _errorMessage.value = null
    }

    fun selectSubjectAndBatch(subjectId: String, batchId: String?) {
        _selectedSubjectAndBatch.value = Pair(subjectId, batchId)
    }

    fun addSyllabusTopic(
        topicName: String,
        subjectId: String,
        description: String?
    ) {
        _isLoading.value = true
        _errorMessage.value = null
        viewModelScope.launch(Dispatchers.IO) {
            try {
                // Determine the next order automatically
                val existingTopics = syllabusTopicRepository.getTopicsForSubject(subjectId).firstOrNull() ?: emptyList()
                // Find the maximum existing order, default to 0 if no topics or all orders are null
                val maxOrder = existingTopics.maxOfOrNull { it.order ?: 0 } ?: 0
                val autoGeneratedOrder = maxOrder + 1

                val newTopic = SyllabusTopic(
                    id = "",
                    topicName = topicName,
                    subjectId = subjectId,
                    description = description,
                    order = autoGeneratedOrder // Assign the auto-generated order
                )
                val newRowId = syllabusTopicRepository.insertSyllabusTopic(newTopic)
                withContext(Dispatchers.Main) {
                    if (newRowId.isNotBlank()) {
                        _errorMessage.value = "Topic added successfully."
                    } else {
                        _errorMessage.value = "Failed to add topic."
                    }
                }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    _errorMessage.value = "Error adding topic: ${e.message}"
                }
                Log.e(TAG, "Error adding syllabus topic", e)
            } finally {
                withContext(Dispatchers.Main) {
                    _isLoading.value = false
                }
            }
        }
    }

    fun updateSyllabusTopic(topic: SyllabusTopic) {
        _isLoading.value = true
        _errorMessage.value = null
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val rowsAffected = syllabusTopicRepository.updateSyllabusTopic(topic)
                withContext(Dispatchers.Main) {
                    if (rowsAffected > 0) {
                        _errorMessage.value = "Topic updated successfully."
                    } else {
                        _errorMessage.value = "Failed to update topic."
                    }
                }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    _errorMessage.value = "Error updating topic: ${e.message}"
                }
                Log.e(TAG, "Error updating syllabus topic", e)
            } finally {
                withContext(Dispatchers.Main) {
                    _isLoading.value = false
                }
            }
        }
    }

    fun deleteSyllabusTopic(topicId: String) {
        _isLoading.value = true
        _errorMessage.value = null
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val rowsAffected = syllabusTopicRepository.deleteSyllabusTopicById(topicId)
                withContext(Dispatchers.Main) {
                    if (rowsAffected > 0) {
                        _errorMessage.value = "Topic deleted successfully."
                    } else {
                        _errorMessage.value = "Failed to delete topic."
                    }
                }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    _errorMessage.value = "Error deleting topic: ${e.message}"
                }
                Log.e(TAG, "Error deleting syllabus topic", e)
            } finally {
                withContext(Dispatchers.Main) {
                    _isLoading.value = false
                }
            }
        }
    }

    /**
     * Updates the completion status of a syllabus topic for a specific batch.
     * If a progress record exists, it updates it; otherwise, it creates a new one.
     * @param topicId The ID of the syllabus topic.
     * @param batchId The ID of the batch.
     * @param isCompleted True if the topic is completed, false otherwise.
     * @param updatedByTeacherId The ID of the teacher who updated the status.
     */
    fun updateSyllabusProgress(
        topicId: String,
        batchId: String,
        isCompleted: Boolean,
        updatedByTeacherId: String
    ) {
        _isLoading.value = true
        _errorMessage.value = null
        viewModelScope.launch(Dispatchers.IO) {
            try {
                // The SyllabusProgress model will automatically handle if 'remarks' and 'completionDate' are null for uncompleted.
                // It will store composite ID "topicId_batchId" internally for upsert.
                val progress = SyllabusProgress(
                    syllabusTopicId = topicId,
                    batchId = batchId,
                    isCompleted = isCompleted,
                    completionDate = if (isCompleted) SimpleDateFormat("yyyy-MM-dd", Locale.US).format(Date()) else null,
                    updatedByTeacherId = updatedByTeacherId,
                    remarks = null // Or pass remarks from UI if available
                )
                // syllabusProgressRepository.insertSyllabusProgress performs an upsert
                val upsertedId = syllabusProgressRepository.insertSyllabusProgress(progress)

                withContext(Dispatchers.Main) {
                    if (upsertedId.isNotBlank()) {
                        _errorMessage.value = "Syllabus progress updated."
                    } else {
                        _errorMessage.value = "Failed to update syllabus progress."
                    }
                }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    _errorMessage.value = "Error updating syllabus progress: ${e.message}"
                }
                Log.e(TAG, "Error updating syllabus progress", e)
            } finally {
                withContext(Dispatchers.Main) {
                    _isLoading.value = false
                }
            }
        }
    }

    /**
     * Reindexes all syllabus topics for a given subject, assigning them sequential orders.
     * Topics are sorted by name alphabetically before re-indexing.
     * @param subjectId The ID of the subject whose topics need reordering.
     */
    fun reindexSyllabusTopicsForSubject(subjectId: String) {
        _isLoading.value = true
        _errorMessage.value = null
        viewModelScope.launch(Dispatchers.IO) {
            try {
                val currentTopics = syllabusTopicRepository.getTopicsForSubject(subjectId).firstOrNull() ?: emptyList()

                if (currentTopics.isEmpty()) {
                    withContext(Dispatchers.Main) {
                        _errorMessage.value = "No topics to reorder for this subject."
                    }
                    return@launch
                }

                // Sort topics by topicName to establish a consistent order for re-indexing
                val sortedTopics = currentTopics.sortedBy { it.topicName }

                var successCount = 0
                for ((index, topic) in sortedTopics.withIndex()) {
                    val newOrder = index + 1
                    val updatedTopic = topic.copy(order = newOrder)
                    val rowsAffected = syllabusTopicRepository.updateSyllabusTopic(updatedTopic)
                    if (rowsAffected > 0) {
                        successCount++
                    }
                }

                withContext(Dispatchers.Main) {
                    _errorMessage.value = "Successfully reordered $successCount topics for this subject."
                }
            } catch (e: Exception) {
                withContext(Dispatchers.Main) {
                    _errorMessage.value = "Error reordering topics: ${e.message}"
                }
                Log.e(TAG, "Error reordering syllabus topics", e)
            } finally {
                withContext(Dispatchers.Main) {
                    _isLoading.value = false
                }
            }
        }
    }
}